export const manufacturers = [
    "Ursus",
    "Timisoreana",
    "Carlsberg",
    "Neumarkt",
    "Stella",
    "Heineken",
    "Beck",
    "Tuborg",
    "Holsten",
    "Peroni",
    "Staropramen",
    "Skol",
    "Azuga",
    "Grolsch",
    "Ciuc",
    "Ciucas",
    "Pilsner Urquell",
    "Bergenbier",
    "Guiness",
    "Asahi",
    "Kozel",
]